export type ExpandedQuestion = {
  subject: string;
  topic: string;
  subtopic: string;
  roundType: string;
  difficulty: string;
  timeLimitSeconds: number;
  questionText: string;
  answer: string;
  acceptedAnswers: string[];
  shortcutSolution: string;
  fullSolution: string;
  commonTrap: string;
  encouragement: string;
  repeatedPattern: string;
  patternFamily: string;
  tags: string[];
  ghanaContext: boolean;
  examinerFocus?: string;
  markingScheme?: string;
  riddleClues?: { clueNumber: number; clueText: string; points: number }[];
};

const encouragement = "You missed the pattern, not the whole topic. Try 3 more from this pattern.";
const clues = (values: string[]) => {
  const points = [5, 4, 3, 3, 3];
  return values.map((clueText, index) => ({ clueNumber: index + 1, clueText, points: points[index] }));
};
const q = (question: Omit<ExpandedQuestion, "encouragement" | "acceptedAnswers" | "tags" | "ghanaContext"> & Partial<Pick<ExpandedQuestion, "acceptedAnswers" | "tags" | "ghanaContext">>): ExpandedQuestion => ({
  acceptedAnswers: [],
  tags: [question.topic.toLowerCase()],
  ghanaContext: false,
  encouragement,
  ...question,
});

export const expandedQuestions: ExpandedQuestion[] = [
  // Mathematics: 4 easy, 6 medium, 8 hard, 2 final
  q({ subject: "MATHEMATICS", topic: "Algebra", subtopic: "Linear equations", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 15, questionText: "Solve 5x - 7 = 18.", answer: "5", shortcutSolution: "Add 7 and divide by 5: x = 25/5.", fullSolution: "5x - 7 = 18 gives 5x = 25, hence x = 5.", commonTrap: "Dividing 18 by 5 before moving the constant.", repeatedPattern: "linear equation isolation", patternFamily: "linear equations" }),
  q({ subject: "MATHEMATICS", topic: "Mensuration", subtopic: "Rectangles", roundType: "ROUND_ONE", difficulty: "EASY", timeLimitSeconds: 25, questionText: "A rectangular kente panel is 1.8 m long and 0.5 m wide. Find its area.", answer: "0.9 m²", acceptedAnswers: ["0.9", "0.9m2"], shortcutSolution: "Area = 1.8 × 0.5 = 0.9 m².", fullSolution: "The area of a rectangle is length multiplied by width.", commonTrap: "Adding the dimensions instead of multiplying.", repeatedPattern: "rectangle area", patternFamily: "mensuration", ghanaContext: true, tags: ["kente", "area"] }),
  q({ subject: "MATHEMATICS", topic: "Sequences and Series", subtopic: "Geometric progression", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 18, questionText: "Find the next term: 3, 6, 12, 24, ...", answer: "48", shortcutSolution: "Each term doubles.", fullSolution: "The common ratio is 2, so 24 × 2 = 48.", commonTrap: "Adding a constant difference.", repeatedPattern: "identify geometric ratio", patternFamily: "sequences" }),
  q({ subject: "MATHEMATICS", topic: "Statistics and Probability", subtopic: "Mean", roundType: "TRUE_FALSE", difficulty: "EASY", timeLimitSeconds: 20, questionText: "True or False: The mean of 2, 4, 6 and 8 is 5.", answer: "True", acceptedAnswers: ["T"], shortcutSolution: "Sum 20 divided by 4 gives 5.", fullSolution: "Arithmetic mean = (2 + 4 + 6 + 8)/4 = 5.", commonTrap: "Dividing by the largest value rather than the number of values.", repeatedPattern: "calculate arithmetic mean", patternFamily: "descriptive statistics" }),
  q({ subject: "MATHEMATICS", topic: "Geometry", subtopic: "Symmetry", roundType: "ROUND_ONE", difficulty: "MEDIUM", timeLimitSeconds: 35, questionText: "A square Adinkra tile is rotated through 90° about its centre. What order of rotational symmetry does the square have?", answer: "4", shortcutSolution: "It matches itself four times in 360°.", fullSolution: "A square coincides with itself at 90°, 180°, 270°, and 360°, so its rotational order is 4.", commonTrap: "Counting only positions before 360°.", repeatedPattern: "rotational symmetry order", patternFamily: "transformations", ghanaContext: true, tags: ["adinkra", "symmetry"] }),
  q({ subject: "MATHEMATICS", topic: "Coordinate Geometry", subtopic: "Gradient", roundType: "SPEED_RACE", difficulty: "MEDIUM", timeLimitSeconds: 20, questionText: "Find the gradient of the line through (2, 3) and (6, 11).", answer: "2", shortcutSolution: "(11 - 3)/(6 - 2) = 8/4.", fullSolution: "Gradient equals change in y divided by change in x, giving 2.", commonTrap: "Reversing one subtraction but not the other.", repeatedPattern: "two-point gradient", patternFamily: "straight lines" }),
  q({ subject: "MATHEMATICS", topic: "Trigonometry", subtopic: "Right triangles", roundType: "ROUND_ONE", difficulty: "MEDIUM", timeLimitSeconds: 40, questionText: "A ladder 5 m long reaches 4 m up a wall. How far is its foot from the wall?", answer: "3 m", acceptedAnswers: ["3", "3m"], shortcutSolution: "Recognize the 3-4-5 triangle.", fullSolution: "By Pythagoras, horizontal distance = √(5² - 4²) = √9 = 3 m.", commonTrap: "Adding the squares instead of subtracting from the hypotenuse.", repeatedPattern: "missing side in right triangle", patternFamily: "Pythagoras" }),
  q({ subject: "MATHEMATICS", topic: "Logarithms", subtopic: "Change of base", roundType: "TRUE_FALSE", difficulty: "MEDIUM", timeLimitSeconds: 25, questionText: "True or False: log₂8 = log₁₀8 ÷ log₁₀2.", answer: "True", acceptedAnswers: ["T"], shortcutSolution: "This is exactly the change-of-base formula.", fullSolution: "For valid bases, logₐb = log_cb/log_ca, so the statement is true.", commonTrap: "Multiplying the logarithms instead of dividing.", repeatedPattern: "recognize change of base", patternFamily: "logarithm laws" }),
  q({ subject: "MATHEMATICS", topic: "Vectors", subtopic: "Magnitude", roundType: "SPEED_RACE", difficulty: "MEDIUM", timeLimitSeconds: 20, questionText: "Find the magnitude of the vector 6i + 8j.", answer: "10", shortcutSolution: "√(6² + 8²) = √100.", fullSolution: "The Euclidean magnitude is √(36 + 64) = 10.", commonTrap: "Adding components directly.", repeatedPattern: "2D vector magnitude", patternFamily: "vectors" }),
  q({ subject: "MATHEMATICS", topic: "Algebra", subtopic: "Indices", roundType: "RIDDLE", difficulty: "MEDIUM", timeLimitSeconds: 60, questionText: "Identify the mathematical operation from the clues.", answer: "square root", acceptedAnswers: ["a square root", "square rooting"], shortcutSolution: "It reverses squaring.", fullSolution: "The square root of a number is a value that gives the number when multiplied by itself.", commonTrap: "Answering reciprocal, which reverses multiplication rather than squaring.", repeatedPattern: "identify inverse operation", patternFamily: "indices and roots", riddleClues: clues(["I undo a familiar power operation.", "For positive numbers I have a principal non-negative value.", "If x² = a, I help recover x.", "My symbol is √."]) }),
  q({ subject: "MATHEMATICS", topic: "Calculus", subtopic: "Stationary points", roundType: "ROUND_ONE", difficulty: "HARD", timeLimitSeconds: 50, questionText: "Find the x-coordinate of the stationary point of y = x² - 8x + 3.", answer: "4", shortcutSolution: "For ax² + bx + c, the vertex has x = -b/2a = 4.", fullSolution: "dy/dx = 2x - 8. Setting this equal to zero gives x = 4.", commonTrap: "Substituting x = 4 back and reporting the y-coordinate instead.", repeatedPattern: "quadratic stationary point", patternFamily: "differentiation" }),
  q({ subject: "MATHEMATICS", topic: "Statistics and Probability", subtopic: "Conditional probability", roundType: "ROUND_ONE", difficulty: "HARD", timeLimitSeconds: 55, questionText: "A bag has 5 red and 3 blue counters. Two are drawn without replacement. Find the probability that both are blue.", answer: "3/28", acceptedAnswers: ["0.107142857"], shortcutSolution: "3/8 × 2/7 = 6/56 = 3/28.", fullSolution: "Without replacement, the blue probabilities are 3/8 then 2/7. Their product is 3/28.", commonTrap: "Using 3/8 twice as if replacement occurred.", repeatedPattern: "without-replacement probability", patternFamily: "conditional probability" }),
  q({ subject: "MATHEMATICS", topic: "Algebra", subtopic: "Simultaneous equations", roundType: "SPEED_RACE", difficulty: "HARD", timeLimitSeconds: 30, questionText: "If x + y = 11 and x - y = 3, find xy.", answer: "28", shortcutSolution: "Add equations: x = 7; then y = 4; product 28.", fullSolution: "Solving simultaneously gives x = 7 and y = 4, so xy = 28.", commonTrap: "Reporting x or y instead of their product.", repeatedPattern: "sum-difference simultaneous equations", patternFamily: "simultaneous equations" }),
  q({ subject: "MATHEMATICS", topic: "Geometry", subtopic: "Circle theorems", roundType: "TRUE_FALSE", difficulty: "HARD", timeLimitSeconds: 30, questionText: "True or False: Opposite angles of every cyclic quadrilateral are equal.", answer: "False", acceptedAnswers: ["F"], shortcutSolution: "They are supplementary, not generally equal.", fullSolution: "Opposite angles in a cyclic quadrilateral add to 180°. They are equal only in special cases.", commonTrap: "Confusing cyclic quadrilaterals with parallelograms.", repeatedPattern: "cyclic quadrilateral theorem", patternFamily: "circle geometry" }),
  q({ subject: "MATHEMATICS", topic: "Mensuration", subtopic: "Similar solids", roundType: "ROUND_ONE", difficulty: "HARD", timeLimitSeconds: 55, questionText: "Two similar containers have corresponding lengths in the ratio 2:3. Find the ratio of their volumes.", answer: "8:27", shortcutSolution: "Cube the length ratio: 2³:3³.", fullSolution: "Volumes of similar solids scale with the cube of corresponding linear dimensions.", commonTrap: "Squaring the ratio, which applies to area.", repeatedPattern: "similar-solid volume scale", patternFamily: "similarity" }),
  q({ subject: "MATHEMATICS", topic: "Sequences and Series", subtopic: "Finite series", roundType: "PROBLEM_OF_THE_DAY", difficulty: "HARD", timeLimitSeconds: 300, questionText: "A trader saves GH₵20 in week 1 and increases the weekly amount by GH₵5. Find the amount saved in week 24 and the total saved over 24 weeks.", answer: "GH₵135 and GH₵1,860", acceptedAnswers: ["135 and 1860", "GHS 135, GHS 1860"], shortcutSolution: "a₂₄ = 20 + 23(5) = 135; S₂₄ = 12(20 + 135) = 1,860.", fullSolution: "The savings form an AP with a = 20, d = 5, n = 24. The 24th term is 135 and the sum is n/2(a + l) = 1,860.", commonTrap: "Using 24 differences instead of 23.", repeatedPattern: "AP term and sum", patternFamily: "arithmetic series", ghanaContext: true, examinerFocus: "Translate a savings pattern into an arithmetic progression and calculate both term and sum.", markingScheme: "4 marks 24th term; 4 marks series sum; 2 marks units and interpretation." }),
  q({ subject: "MATHEMATICS", topic: "Coordinate Geometry", subtopic: "Circle equation", roundType: "RIDDLE", difficulty: "HARD", timeLimitSeconds: 60, questionText: "Identify the curve from the clues.", answer: "circle", acceptedAnswers: ["a circle"], shortcutSolution: "A fixed distance from one fixed point defines a circle.", fullSolution: "A circle is the locus of points at a constant distance, the radius, from a fixed centre.", commonTrap: "Answering sphere, which is the three-dimensional analogue.", repeatedPattern: "identify locus from definition", patternFamily: "coordinate loci", riddleClues: clues(["I am a closed plane curve.", "Every point on me obeys one distance condition.", "My standard equation contains (x-a)² + (y-b)².", "I have a centre and a radius."]) }),
  q({ subject: "MATHEMATICS", topic: "Trigonometry", subtopic: "Bearings", roundType: "PROBLEM_OF_THE_DAY", difficulty: "HARD", timeLimitSeconds: 300, questionText: "A fishing boat travels 12 km east, then 5 km north. Find its distance and three-figure bearing from the starting point.", answer: "13 km; 067°", acceptedAnswers: ["13 km, 67 degrees", "13, 067"], shortcutSolution: "Distance uses the 5-12-13 triangle; bearing θ = tan⁻¹(12/5) ≈ 67.4°.", fullSolution: "The displacement is √(12²+5²)=13 km. Bearing is measured clockwise from north, so tan θ = east/north = 12/5, giving about 067°.", commonTrap: "Measuring the angle from east and reporting 023°.", repeatedPattern: "resultant displacement and bearing", patternFamily: "navigation trigonometry", ghanaContext: true, examinerFocus: "Combine Pythagoras with the bearing convention.", markingScheme: "4 marks diagram/components; 3 marks distance; 3 marks bearing." }),
  q({ subject: "MATHEMATICS", topic: "Calculus", subtopic: "Integration", roundType: "PROBLEM_OF_THE_DAY", difficulty: "NSMQ_FINAL_LEVEL", timeLimitSeconds: 360, questionText: "The curve y = 6x - x² meets the x-axis at x = 0 and x = 6. Find the enclosed area and the x-coordinate of the curve's maximum.", answer: "36 square units; x = 3", acceptedAnswers: ["36, 3"], shortcutSolution: "Area = [3x² - x³/3]₀⁶ = 36; vertex x = -6/(2×-1) = 3.", fullSolution: "Integrating from 0 to 6 gives 36 square units. Differentiating gives 6 - 2x = 0, hence the maximum occurs at x = 3.", commonTrap: "Finding only the rectangle under the maximum or forgetting limits.", repeatedPattern: "area under quadratic and maximum", patternFamily: "calculus synthesis", examinerFocus: "Link definite integration and differentiation on one quadratic.", markingScheme: "6 marks area; 3 marks stationary point; 1 mark interpretation." }),
  q({ subject: "MATHEMATICS", topic: "Statistics and Probability", subtopic: "Bayes theorem", roundType: "PROBLEM_OF_THE_DAY", difficulty: "NSMQ_FINAL_LEVEL", timeLimitSeconds: 360, questionText: "Machines A and B make 60% and 40% of a factory's bulbs. Their defect rates are 2% and 5%. A bulb is defective. Find the probability it came from B.", answer: "5/8", acceptedAnswers: ["0.625", "62.5%"], shortcutSolution: "B-defects = .4(.05)=.02; total defects=.6(.02)+.4(.05)=.032; ratio=.02/.032=5/8.", fullSolution: "Using Bayes' theorem, P(B|D)=P(B)P(D|B)/P(D)=0.02/(0.012+0.02)=0.625.", commonTrap: "Giving the 5% defect rate as the required conditional probability.", repeatedPattern: "reverse conditional probability", patternFamily: "Bayes theorem", examinerFocus: "Distinguish a source's defect rate from the source probability given a defect.", markingScheme: "3 marks weighted defect probabilities; 4 marks total; 3 marks conditional result." }),

  // Physics: 4 easy, 6 medium, 8 hard, 2 final
  q({ subject: "PHYSICS", topic: "Measurement and Units", subtopic: "SI units", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 15, questionText: "What is the SI unit of electric charge?", answer: "coulomb", acceptedAnswers: ["C", "coulombs"], shortcutSolution: "Charge is measured in coulombs.", fullSolution: "The SI derived unit of electric charge is the coulomb, symbol C.", commonTrap: "Answering ampere, the unit of current.", repeatedPattern: "quantity-to-unit recall", patternFamily: "SI units" }),
  q({ subject: "PHYSICS", topic: "Mechanics", subtopic: "Average speed", roundType: "ROUND_ONE", difficulty: "EASY", timeLimitSeconds: 30, questionText: "A trotro covers 36 km in 45 minutes. Find its average speed in km/h.", answer: "48 km/h", acceptedAnswers: ["48", "48km/h"], shortcutSolution: "45 min = 0.75 h; 36/0.75 = 48.", fullSolution: "Average speed is distance divided by time: 36 km ÷ 0.75 h = 48 km/h.", commonTrap: "Dividing by 45 without converting minutes to hours.", repeatedPattern: "average speed with time conversion", patternFamily: "kinematics", ghanaContext: true, tags: ["trotro", "speed"] }),
  q({ subject: "PHYSICS", topic: "Heat and Thermodynamics", subtopic: "Heat transfer", roundType: "TRUE_FALSE", difficulty: "EASY", timeLimitSeconds: 20, questionText: "True or False: Stirring waakye helps distribute thermal energy through the food by forced convection.", answer: "True", acceptedAnswers: ["T"], shortcutSolution: "Stirring drives bulk fluid motion, which is forced convection.", fullSolution: "The spoon creates circulation that transports thermal energy through the liquid portions of the food.", commonTrap: "Calling all heating conduction because a metal pot is involved.", repeatedPattern: "identify heat-transfer mode", patternFamily: "thermal transfer", ghanaContext: true, tags: ["waakye", "convection"] }),
  q({ subject: "PHYSICS", topic: "Electricity", subtopic: "Electrical power", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 18, questionText: "A 12 V lamp draws 2 A. Find its electrical power.", answer: "24 W", acceptedAnswers: ["24", "24W"], shortcutSolution: "P = VI = 12 × 2.", fullSolution: "Electrical power equals potential difference times current, giving 24 W.", commonTrap: "Using V/I, which gives resistance.", repeatedPattern: "electrical power product", patternFamily: "DC electricity" }),
  q({ subject: "PHYSICS", topic: "Pressure and Fluids", subtopic: "Density", roundType: "ROUND_ONE", difficulty: "MEDIUM", timeLimitSeconds: 40, questionText: "A gold sample has mass 386 g and volume 20 cm³. Find its density.", answer: "19.3 g/cm³", acceptedAnswers: ["19.3", "19300 kg/m3"], shortcutSolution: "Density = 386/20 = 19.3 g/cm³.", fullSolution: "Density is mass per unit volume. The result is consistent with gold's high density.", commonTrap: "Dividing volume by mass.", repeatedPattern: "density from mass and volume", patternFamily: "material properties", ghanaContext: true, tags: ["gold", "density"] }),
  q({ subject: "PHYSICS", topic: "Optics", subtopic: "Refraction", roundType: "ROUND_ONE", difficulty: "MEDIUM", timeLimitSeconds: 45, questionText: "Light travels from air into water. Does it bend toward or away from the normal?", answer: "toward the normal", acceptedAnswers: ["towards the normal"], shortcutSolution: "Entering the optically denser medium slows light, so it bends toward the normal.", fullSolution: "Water has a larger refractive index than air; Snell's law therefore gives a smaller refracted angle.", commonTrap: "Using the rule for light leaving water.", repeatedPattern: "refraction direction", patternFamily: "geometrical optics" }),
  q({ subject: "PHYSICS", topic: "Waves", subtopic: "Sound", roundType: "TRUE_FALSE", difficulty: "MEDIUM", timeLimitSeconds: 22, questionText: "True or False: Increasing a sound wave's amplitude normally increases its loudness without changing its pitch.", answer: "True", acceptedAnswers: ["T"], shortcutSolution: "Amplitude controls loudness; frequency controls pitch.", fullSolution: "For the same medium and waveform, greater amplitude means greater intensity, while unchanged frequency means unchanged pitch.", commonTrap: "Interchanging amplitude and frequency effects.", repeatedPattern: "wave property to perception", patternFamily: "sound waves" }),
  q({ subject: "PHYSICS", topic: "Magnetism", subtopic: "Magnetic fields", roundType: "SPEED_RACE", difficulty: "MEDIUM", timeLimitSeconds: 20, questionText: "Name the physical quantity measured in tesla.", answer: "magnetic flux density", acceptedAnswers: ["B field", "magnetic field strength B"], shortcutSolution: "Tesla is the SI unit of B, magnetic flux density.", fullSolution: "Magnetic flux density B is measured in tesla, T.", commonTrap: "Answering magnetic flux, which is measured in webers.", repeatedPattern: "magnetic quantity from unit", patternFamily: "electromagnetism" }),
  q({ subject: "PHYSICS", topic: "Electronics", subtopic: "Diodes", roundType: "TRUE_FALSE", difficulty: "MEDIUM", timeLimitSeconds: 25, questionText: "True or False: An ideal diode conducts equally well in both directions.", answer: "False", acceptedAnswers: ["F"], shortcutSolution: "A diode is designed for one-way conduction.", fullSolution: "An ideal diode conducts with zero resistance when forward biased and blocks current when reverse biased.", commonTrap: "Confusing a diode with an ordinary resistor.", repeatedPattern: "ideal diode behavior", patternFamily: "semiconductor devices" }),
  q({ subject: "PHYSICS", topic: "Modern Physics", subtopic: "Photons", roundType: "RIDDLE", difficulty: "MEDIUM", timeLimitSeconds: 60, questionText: "Identify the quantum object from the clues.", answer: "photon", acceptedAnswers: ["a photon", "photons"], shortcutSolution: "A massless quantum with energy hf is a photon.", fullSolution: "A photon is a quantum of electromagnetic radiation carrying energy E = hf and momentum h/λ.", commonTrap: "Answering electron, which has rest mass and electric charge.", repeatedPattern: "identify quantum particle", patternFamily: "quantum physics", riddleClues: clues(["I carry energy across empty space.", "I have no electric charge and no rest mass.", "My energy is proportional to frequency.", "I am a quantum of electromagnetic radiation."]) }),
  q({ subject: "PHYSICS", topic: "Mechanics", subtopic: "Trotro acceleration", roundType: "ROUND_ONE", difficulty: "HARD", timeLimitSeconds: 50, questionText: "A trotro slows uniformly from 20 m/s to 8 m/s in 4 s. Find its acceleration and distance travelled.", answer: "-3 m/s²; 56 m", acceptedAnswers: ["-3, 56"], shortcutSolution: "a=(8-20)/4=-3; average speed=(20+8)/2=14, so s=56.", fullSolution: "Uniform acceleration permits use of a = Δv/t and distance = average velocity × time.", commonTrap: "Using final speed alone to calculate distance.", repeatedPattern: "uniform deceleration and distance", patternFamily: "SUVAT", ghanaContext: true, tags: ["trotro", "acceleration"] }),
  q({ subject: "PHYSICS", topic: "Electricity", subtopic: "Series-parallel circuits", roundType: "ROUND_ONE", difficulty: "HARD", timeLimitSeconds: 55, questionText: "A 6 Ω resistor is in parallel with 3 Ω, and the combination is in series with 4 Ω. Find the total resistance.", answer: "6 Ω", acceptedAnswers: ["6 ohms", "6"], shortcutSolution: "Parallel part = (6×3)/(6+3)=2 Ω; add 4 Ω.", fullSolution: "The parallel equivalent is 2 Ω. Series resistances add, giving 6 Ω total.", commonTrap: "Adding all three resistances directly.", repeatedPattern: "mixed resistor network", patternFamily: "DC circuits" }),
  q({ subject: "PHYSICS", topic: "Heat and Thermodynamics", subtopic: "Evaporative cooling", roundType: "TRUE_FALSE", difficulty: "HARD", timeLimitSeconds: 30, questionText: "True or False: Water in a porous clay pot may cool because the highest-energy molecules escape during evaporation.", answer: "True", acceptedAnswers: ["T"], shortcutSolution: "Evaporation removes above-average kinetic energy.", fullSolution: "Water seeping to the outer surface evaporates; energetic molecules leave and lower the mean kinetic energy of the remaining water.", commonTrap: "Saying the clay itself creates cold.", repeatedPattern: "molecular explanation of cooling", patternFamily: "thermal physics", ghanaContext: true, tags: ["clay pot", "evaporation"] }),
  q({ subject: "PHYSICS", topic: "Waves", subtopic: "Standing waves", roundType: "ROUND_ONE", difficulty: "HARD", timeLimitSeconds: 50, questionText: "A string fixed at both ends has length 1.2 m. Find the wavelength of its fundamental mode.", answer: "2.4 m", acceptedAnswers: ["2.4", "2.4m"], shortcutSolution: "Fundamental has half a wavelength on the string: λ = 2L.", fullSolution: "For a fixed-fixed string in its first harmonic, L = λ/2, so λ = 2.4 m.", commonTrap: "Taking wavelength equal to the string length.", repeatedPattern: "fundamental standing wavelength", patternFamily: "standing waves" }),
  q({ subject: "PHYSICS", topic: "Pressure and Fluids", subtopic: "Hydrostatic pressure", roundType: "SPEED_RACE", difficulty: "HARD", timeLimitSeconds: 30, questionText: "Find the gauge pressure 5 m below fresh water. Use ρ = 1000 kg/m³ and g = 10 m/s².", answer: "50000 Pa", acceptedAnswers: ["50 kPa", "5 x 10^4 Pa"], shortcutSolution: "ρgh = 1000×10×5.", fullSolution: "Hydrostatic gauge pressure is ρgh = 50,000 Pa.", commonTrap: "Adding atmospheric pressure when gauge pressure is requested.", repeatedPattern: "hydrostatic pressure", patternFamily: "fluid statics" }),
  q({ subject: "PHYSICS", topic: "Magnetism", subtopic: "Electromagnetic induction", roundType: "RIDDLE", difficulty: "HARD", timeLimitSeconds: 60, questionText: "Identify the law from the clues.", answer: "Faraday's law", acceptedAnswers: ["Faraday law", "law of electromagnetic induction"], shortcutSolution: "Changing magnetic flux inducing emf identifies Faraday's law.", fullSolution: "Faraday's law states that induced emf is proportional to the rate of change of magnetic flux linkage.", commonTrap: "Answering Lenz's law, which gives the direction rather than magnitude relation.", repeatedPattern: "identify induction law", patternFamily: "electromagnetic induction", riddleClues: clues(["I connect electricity and changing magnetism.", "I concern a circuit's flux linkage.", "My equation contains a time derivative and a minus sign.", "I state that changing magnetic flux induces emf."]) }),
  q({ subject: "PHYSICS", topic: "Mechanics", subtopic: "Hydroelectric energy", roundType: "PROBLEM_OF_THE_DAY", difficulty: "HARD", timeLimitSeconds: 300, questionText: "At a hydroelectric station, water falls through 75 m at 500 kg/s. If g = 10 m/s² and efficiency is 80%, find input power and electrical output power.", answer: "375 kW; 300 kW", acceptedAnswers: ["375000 W, 300000 W"], shortcutSolution: "P=ṁgh=500×10×75=375 kW; output=0.8×375=300 kW.", fullSolution: "The gravitational energy supplied per second is ṁgh. Multiplying by efficiency gives the electrical output.", commonTrap: "Applying efficiency twice or using total mass instead of mass flow rate.", repeatedPattern: "power from mass flow and head", patternFamily: "energy conversion", ghanaContext: true, tags: ["Akosombo", "hydroelectric"], examinerFocus: "Use mass flow rate in gravitational power and apply efficiency correctly.", markingScheme: "5 marks input power; 3 marks efficiency; 2 marks output and units." }),
  q({ subject: "PHYSICS", topic: "Electricity", subtopic: "Kirchhoff laws", roundType: "PROBLEM_OF_THE_DAY", difficulty: "HARD", timeLimitSeconds: 320, questionText: "A 12 V battery with internal resistance 1 Ω is connected to parallel resistors 6 Ω and 3 Ω. Find the external equivalent resistance, total current, terminal voltage, and current in each branch.", answer: "2 Ω; 4 A; 8 V; 4/3 A and 8/3 A", acceptedAnswers: ["2, 4, 8, 1.33, 2.67"], shortcutSolution: "External R=2 Ω; total R=3 Ω; I=4 A; terminal V=12-4(1)=8 V; branch currents V/R.", fullSolution: "Combine the parallel resistors, include internal resistance in series, then apply Ohm's law and current division.", commonTrap: "Using 12 V across the parallel network despite internal voltage loss.", repeatedPattern: "battery internal resistance with parallel load", patternFamily: "circuit synthesis", examinerFocus: "Separate emf from terminal voltage and apply parallel-circuit relations.", markingScheme: "2 marks external R; 2 marks total current; 3 marks terminal voltage; 3 marks branches." }),
  q({ subject: "PHYSICS", topic: "Modern Physics", subtopic: "Photoelectric effect", roundType: "PROBLEM_OF_THE_DAY", difficulty: "NSMQ_FINAL_LEVEL", timeLimitSeconds: 360, questionText: "Light of frequency 8.0×10¹⁴ Hz falls on a metal of work function 2.0 eV. Using h = 6.63×10⁻³⁴ J s and 1 eV = 1.60×10⁻¹⁹ J, find the maximum kinetic energy in joules and eV.", answer: "2.104×10⁻¹⁹ J; 1.315 eV", acceptedAnswers: ["2.10e-19 J, 1.32 eV"], shortcutSolution: "hf=5.304×10⁻¹⁹ J; subtract 3.20×10⁻¹⁹ J; divide by 1.60×10⁻¹⁹ for eV.", fullSolution: "Einstein's equation Kmax = hf - φ gives 2.104×10⁻¹⁹ J, equivalent to about 1.315 eV.", commonTrap: "Subtracting 2.0 directly from energy measured in joules.", repeatedPattern: "photoelectric energy balance", patternFamily: "quantum calculations", examinerFocus: "Keep energy units consistent in the photoelectric equation.", markingScheme: "3 marks photon energy; 2 marks conversion; 3 marks kinetic energy; 2 marks eV result." }),
  q({ subject: "PHYSICS", topic: "Mechanics", subtopic: "Rotational dynamics", roundType: "PROBLEM_OF_THE_DAY", difficulty: "NSMQ_FINAL_LEVEL", timeLimitSeconds: 360, questionText: "A uniform 2.0 m beam of mass 12 kg is hinged at one end and held horizontal by a vertical cable at the other. A 30 kg load hangs 0.5 m from the hinge. Use g = 10 m/s². Find the cable tension and hinge vertical reaction.", answer: "135 N; 285 N", acceptedAnswers: ["135, 285"], shortcutSolution: "Moments: 2T=120(1)+300(0.5)=270, so T=135 N. Vertical balance gives R+135=420.", fullSolution: "Taking moments about the hinge gives the cable tension. Then vertical force equilibrium gives the hinge reaction.", commonTrap: "Placing the beam's weight at the hinge instead of its centre.", repeatedPattern: "beam equilibrium with distributed mass", patternFamily: "statics", examinerFocus: "Use centre of mass, moments, and force equilibrium in sequence.", markingScheme: "5 marks moments/tension; 4 marks force balance; 1 mark direction." }),

  // Chemistry: 3 easy, 6 medium, 8 hard, 3 final
  q({ subject: "CHEMISTRY", topic: "Periodic Chemistry", subtopic: "Halogens", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 15, questionText: "Which Group 17 element is a liquid at room temperature?", answer: "bromine", acceptedAnswers: ["Br2"], shortcutSolution: "Among common halogens, bromine is the room-temperature liquid.", fullSolution: "Fluorine and chlorine are gases, bromine is liquid, and iodine is solid at room conditions.", commonTrap: "Answering mercury, which is a liquid metal.", repeatedPattern: "periodic physical-state recall", patternFamily: "group trends" }),
  q({ subject: "CHEMISTRY", topic: "Acids, Bases, and Salts", subtopic: "Indicators", roundType: "ROUND_ONE", difficulty: "EASY", timeLimitSeconds: 25, questionText: "What colour does blue litmus turn in an acidic solution?", answer: "red", shortcutSolution: "Acid turns blue litmus red.", fullSolution: "Hydrogen ions interact with the indicator, changing blue litmus to red.", commonTrap: "Reversing the acid and alkali colour changes.", repeatedPattern: "indicator colour change", patternFamily: "acid-base identification" }),
  q({ subject: "CHEMISTRY", topic: "Organic Chemistry", subtopic: "Plant hormones", roundType: "TRUE_FALSE", difficulty: "EASY", timeLimitSeconds: 20, questionText: "True or False: Ethene can accelerate the ripening of harvested plantain.", answer: "True", acceptedAnswers: ["T"], shortcutSolution: "Ethene is a gaseous plant hormone that promotes fruit ripening.", fullSolution: "Ethene triggers biochemical changes including softening, colour change, and sugar development.", commonTrap: "Assuming all hydrocarbons are biologically inactive.", repeatedPattern: "organic molecule in biological context", patternFamily: "alkenes", ghanaContext: true, tags: ["plantain", "ethene"] }),
  q({ subject: "CHEMISTRY", topic: "Atomic Structure", subtopic: "Isotopes", roundType: "ROUND_ONE", difficulty: "MEDIUM", timeLimitSeconds: 40, questionText: "Chlorine-35 has atomic number 17. State its numbers of protons, neutrons, and electrons in a neutral atom.", answer: "17 protons, 18 neutrons, 17 electrons", acceptedAnswers: ["17,18,17"], shortcutSolution: "p=17; n=35-17=18; neutral e=17.", fullSolution: "Atomic number gives protons; mass number minus atomic number gives neutrons; neutrality makes electrons equal protons.", commonTrap: "Using mass number as the neutron count.", repeatedPattern: "subatomic counts from nuclide notation", patternFamily: "nuclear notation" }),
  q({ subject: "CHEMISTRY", topic: "Stoichiometry", subtopic: "Concentration", roundType: "SPEED_RACE", difficulty: "MEDIUM", timeLimitSeconds: 20, questionText: "Find the concentration of 0.50 mol solute in 250 cm³ of solution.", answer: "2.0 mol/dm³", acceptedAnswers: ["2", "2 M"], shortcutSolution: "250 cm³ = 0.250 dm³; c = 0.50/0.250.", fullSolution: "Molar concentration is amount divided by volume in dm³, giving 2.0 mol dm⁻³.", commonTrap: "Using 250 directly without converting volume.", repeatedPattern: "moles-volume concentration", patternFamily: "solution chemistry" }),
  q({ subject: "CHEMISTRY", topic: "Chemical Bonding", subtopic: "Intermolecular forces", roundType: "TRUE_FALSE", difficulty: "MEDIUM", timeLimitSeconds: 25, questionText: "True or False: Water has a higher boiling point than hydrogen sulfide mainly because water molecules form hydrogen bonds.", answer: "True", acceptedAnswers: ["T"], shortcutSolution: "O-H bonds permit strong hydrogen bonding.", fullSolution: "Hydrogen bonding between water molecules requires more energy to overcome than the intermolecular forces in H₂S.", commonTrap: "Explaining boiling point only by molar mass.", repeatedPattern: "boiling point from intermolecular force", patternFamily: "molecular interactions" }),
  q({ subject: "CHEMISTRY", topic: "Rates of Reaction", subtopic: "Surface area", roundType: "ROUND_ONE", difficulty: "MEDIUM", timeLimitSeconds: 40, questionText: "Why does powdered calcium carbonate react faster with dilute acid than equal-mass marble chips?", answer: "greater surface area", acceptedAnswers: ["larger surface area", "more exposed surface"], shortcutSolution: "Powder exposes more particles for collisions.", fullSolution: "Greater surface area increases the frequency of effective collisions per second.", commonTrap: "Claiming the powder has more mass.", repeatedPattern: "rate factor explanation", patternFamily: "collision theory" }),
  q({ subject: "CHEMISTRY", topic: "Organic Chemistry", subtopic: "Fermentation", roundType: "ROUND_ONE", difficulty: "MEDIUM", timeLimitSeconds: 45, questionText: "During souring of kenkey dough, microorganisms produce acids. Name the acid commonly associated with lactic fermentation.", answer: "lactic acid", acceptedAnswers: ["2-hydroxypropanoic acid"], shortcutSolution: "Lactic fermentation produces lactic acid.", fullSolution: "Lactic acid bacteria convert fermentable carbohydrates into lactic acid, lowering pH and contributing sourness.", commonTrap: "Answering ethanol, the main product of alcoholic fermentation.", repeatedPattern: "fermentation product from process", patternFamily: "biochemical organic chemistry", ghanaContext: true, tags: ["kenkey", "fermentation"] }),
  q({ subject: "CHEMISTRY", topic: "Chemical Equilibrium", subtopic: "Le Chatelier principle", roundType: "RIDDLE", difficulty: "MEDIUM", timeLimitSeconds: 60, questionText: "Identify the principle from the clues.", answer: "Le Chatelier's principle", acceptedAnswers: ["Le Chatelier principle"], shortcutSolution: "Equilibrium opposing an imposed change identifies Le Chatelier.", fullSolution: "The principle predicts the direction in which an equilibrium shifts after changes in concentration, pressure, or temperature.", commonTrap: "Answering collision theory, which concerns reaction rates.", repeatedPattern: "identify equilibrium principle", patternFamily: "equilibrium response", riddleClues: clues(["I apply to systems that can react in both directions.", "I predict a response to an imposed change.", "Concentration, pressure, and temperature are my common disturbances.", "An equilibrium shifts to oppose the change."]) }),
  q({ subject: "CHEMISTRY", topic: "Electrochemistry", subtopic: "Electrolysis", roundType: "ROUND_ONE", difficulty: "HARD", timeLimitSeconds: 55, questionText: "During electrolysis of molten sodium chloride, name the product at each electrode.", answer: "sodium at cathode; chlorine at anode", acceptedAnswers: ["Na cathode, Cl2 anode"], shortcutSolution: "Na⁺ gains electrons at cathode; Cl⁻ loses electrons at anode.", fullSolution: "Reduction produces sodium metal at the cathode, while oxidation forms chlorine gas at the anode.", commonTrap: "Including water products even though the electrolyte is molten.", repeatedPattern: "molten-electrolyte products", patternFamily: "electrolysis" }),
  q({ subject: "CHEMISTRY", topic: "Thermochemistry", subtopic: "Bond energies", roundType: "ROUND_ONE", difficulty: "HARD", timeLimitSeconds: 60, questionText: "Using H-H = 436, Cl-Cl = 243, and H-Cl = 431 kJ/mol, estimate ΔH for H₂ + Cl₂ → 2HCl.", answer: "-183 kJ/mol", acceptedAnswers: ["-183", "minus 183 kJ/mol"], shortcutSolution: "Break 679; form 862; ΔH=679-862=-183.", fullSolution: "Enthalpy change is total bond energy broken minus total bond energy formed.", commonTrap: "Reversing formed and broken terms.", repeatedPattern: "bond-energy enthalpy estimate", patternFamily: "energetics" }),
  q({ subject: "CHEMISTRY", topic: "Stoichiometry", subtopic: "Gas volumes", roundType: "SPEED_RACE", difficulty: "HARD", timeLimitSeconds: 30, questionText: "At the same temperature and pressure, what volume of oxygen reacts completely with 40 cm³ methane in CH₄ + 2O₂ → CO₂ + 2H₂O(g)?", answer: "80 cm³", acceptedAnswers: ["80", "80cm3"], shortcutSolution: "Gas-volume ratio follows coefficients: 1 volume methane needs 2 oxygen.", fullSolution: "At equal temperature and pressure, reacting gas volumes are proportional to stoichiometric coefficients.", commonTrap: "Using molar masses instead of the gas-volume ratio.", repeatedPattern: "gas volume from equation coefficients", patternFamily: "gas stoichiometry" }),
  q({ subject: "CHEMISTRY", topic: "Acids, Bases, and Salts", subtopic: "Buffer solutions", roundType: "TRUE_FALSE", difficulty: "HARD", timeLimitSeconds: 30, questionText: "True or False: A buffer prevents any pH change regardless of how much strong acid is added.", answer: "False", acceptedAnswers: ["F"], shortcutSolution: "Buffers resist small additions; they have finite capacity.", fullSolution: "A buffer limits pH change only while its conjugate components remain in sufficient amount.", commonTrap: "Treating resistance as absolute prevention.", repeatedPattern: "interpret buffer capacity", patternFamily: "acid-base equilibria" }),
  q({ subject: "CHEMISTRY", topic: "Periodic Chemistry", subtopic: "Transition metals", roundType: "RIDDLE", difficulty: "HARD", timeLimitSeconds: 60, questionText: "Identify the element from the clues.", answer: "iron", acceptedAnswers: ["Fe"], shortcutSolution: "Fe, rust, steel, and haemoglobin point to iron.", fullSolution: "Iron is a transition metal used in steel and present in haem groups; it commonly forms +2 and +3 ions.", commonTrap: "Answering copper, another transition metal with coloured compounds.", repeatedPattern: "identify element from uses and ions", patternFamily: "element properties", riddleClues: clues(["I am a widely used transition metal.", "My compounds often contain ions in two common oxidation states.", "I am central to steel and can form rust.", "My symbol is Fe."]) }),
  q({ subject: "CHEMISTRY", topic: "Organic Chemistry", subtopic: "Immiscibility", roundType: "TRUE_FALSE", difficulty: "HARD", timeLimitSeconds: 28, questionText: "True or False: Palm oil and water form one homogeneous liquid phase because both contain oxygen atoms.", answer: "False", acceptedAnswers: ["F"], shortcutSolution: "Polarity, not merely oxygen presence, controls miscibility.", fullSolution: "Water is strongly polar, while the long hydrocarbon chains in palm-oil triglycerides make the oil predominantly non-polar and immiscible.", commonTrap: "Inferring miscibility from one shared element.", repeatedPattern: "miscibility from molecular polarity", patternFamily: "intermolecular forces", ghanaContext: true, tags: ["palm oil", "liquids"] }),
  q({ subject: "CHEMISTRY", topic: "Stoichiometry", subtopic: "Purity", roundType: "PROBLEM_OF_THE_DAY", difficulty: "HARD", timeLimitSeconds: 300, questionText: "A 5.00 g impure limestone sample reacts with excess acid and produces 0.896 dm³ CO₂ at conditions where molar gas volume is 22.4 dm³/mol. Find the percentage by mass of CaCO₃. Use Mr(CaCO₃)=100.", answer: "80%", acceptedAnswers: ["80 percent", "80.0%"], shortcutSolution: "n(CO₂)=0.896/22.4=0.040 mol, so CaCO₃ mass=4.00 g; purity=4/5×100.", fullSolution: "CaCO₃ and CO₂ react in a 1:1 mole ratio. The gas amount therefore gives 4.00 g pure CaCO₃ in the 5.00 g sample.", commonTrap: "Using gas volume directly as a mass.", repeatedPattern: "purity from gas yield", patternFamily: "quantitative analysis", examinerFocus: "Move from gas volume to moles, reacting mass, then percentage purity.", markingScheme: "3 marks gas moles; 3 marks CaCO₃ mass; 3 marks percentage; 1 mark units." }),
  q({ subject: "CHEMISTRY", topic: "Thermochemistry", subtopic: "Combustion", roundType: "PROBLEM_OF_THE_DAY", difficulty: "HARD", timeLimitSeconds: 300, questionText: "A charcoal stove transfers 1.20 MJ to a pot while 0.050 kg charcoal burns. If charcoal releases 30 MJ/kg, find the energy supplied and the stove efficiency.", answer: "1.50 MJ; 80%", acceptedAnswers: ["1.5 MJ, 80 percent"], shortcutSolution: "Input=0.05×30=1.50 MJ; efficiency=1.20/1.50×100=80%.", fullSolution: "Chemical energy supplied is mass times energy density. Efficiency is useful energy divided by input energy.", commonTrap: "Dividing input by useful energy.", repeatedPattern: "fuel energy and efficiency", patternFamily: "energy changes", ghanaContext: true, tags: ["charcoal", "combustion"], examinerFocus: "Distinguish chemical input energy from useful transferred heat.", markingScheme: "4 marks input energy; 4 marks efficiency; 2 marks interpretation." }),
  q({ subject: "CHEMISTRY", topic: "Electrochemistry", subtopic: "Nernst equation", roundType: "PROBLEM_OF_THE_DAY", difficulty: "NSMQ_FINAL_LEVEL", timeLimitSeconds: 360, questionText: "For Zn(s)|Zn²⁺(0.10 M)||Cu²⁺(1.0 M)|Cu(s), E°cell = 1.10 V at 25°C. Using E = E° - (0.0592/n)log Q, find Ecell.", answer: "1.13 V", acceptedAnswers: ["1.1296 V", "1.130 V"], shortcutSolution: "n=2, Q=[Zn²⁺]/[Cu²⁺]=0.10; log Q=-1, so E=1.10+0.0296.", fullSolution: "The cell reaction produces Zn²⁺ and consumes Cu²⁺. Substitution into the Nernst equation gives 1.1296 V.", commonTrap: "Inverting Q and lowering the voltage.", repeatedPattern: "non-standard cell potential", patternFamily: "electrochemical cells", examinerFocus: "Construct the reaction quotient with correct products and reactants.", markingScheme: "3 marks reaction/Q; 2 marks n; 4 marks substitution; 1 mark rounding." }),
  q({ subject: "CHEMISTRY", topic: "Chemical Equilibrium", subtopic: "Equilibrium constants", roundType: "PROBLEM_OF_THE_DAY", difficulty: "NSMQ_FINAL_LEVEL", timeLimitSeconds: 360, questionText: "For N₂O₄(g) ⇌ 2NO₂(g), 1.00 mol N₂O₄ is placed in a 1.00 dm³ vessel. At equilibrium 0.40 mol N₂O₄ remains. Calculate Kc.", answer: "3.6 mol/dm³", acceptedAnswers: ["3.6", "3.60"], shortcutSolution: "Dissociated=0.60; NO₂ formed=1.20. Kc=(1.20)²/0.40=3.6.", fullSolution: "An ICE table gives equilibrium concentrations [N₂O₄]=0.40 and [NO₂]=1.20 mol dm⁻³, hence Kc=3.6.", commonTrap: "Forming only 0.60 mol NO₂ instead of twice that amount.", repeatedPattern: "Kc from dissociation extent", patternFamily: "equilibrium calculations", examinerFocus: "Use stoichiometric change correctly in an ICE table.", markingScheme: "4 marks equilibrium amounts; 2 marks expression; 4 marks Kc." }),
  q({ subject: "CHEMISTRY", topic: "Organic Chemistry", subtopic: "Reaction pathways", roundType: "PROBLEM_OF_THE_DAY", difficulty: "NSMQ_FINAL_LEVEL", timeLimitSeconds: 360, questionText: "An alkene C₄H₈ gives only one structural alcohol when hydrated and gives two identical carbonyl compounds on oxidative cleavage. Identify the alkene and hydration product.", answer: "but-2-ene; butan-2-ol", acceptedAnswers: ["2-butene and 2-butanol"], shortcutSolution: "Symmetric C₄ alkene that cleaves identically is CH₃CH=CHCH₃.", fullSolution: "But-2-ene is symmetric; hydration gives butan-2-ol, and cleavage across the double bond gives identical two-carbon carbonyl fragments.", commonTrap: "Choosing but-1-ene, which is not symmetric and gives different cleavage products.", repeatedPattern: "deduce alkene from symmetry and products", patternFamily: "organic structure deduction", examinerFocus: "Combine molecular formula, symmetry, addition, and cleavage evidence.", markingScheme: "5 marks alkene deduction; 3 marks alcohol; 2 marks structural justification." }),

  // Biology: 3 easy, 5 medium, 8 hard, 4 final
  q({ subject: "BIOLOGY", topic: "Human Physiology", subtopic: "Blood", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 15, questionText: "Which blood cells transport most oxygen in humans?", answer: "red blood cells", acceptedAnswers: ["erythrocytes", "RBCs"], shortcutSolution: "Haemoglobin is concentrated in red blood cells.", fullSolution: "Erythrocytes carry oxygen bound to haemoglobin.", commonTrap: "Answering white blood cells, which mainly defend against disease.", repeatedPattern: "cell from physiological function", patternFamily: "circulation" }),
  q({ subject: "BIOLOGY", topic: "Plant Biology", subtopic: "Water transport", roundType: "ROUND_ONE", difficulty: "EASY", timeLimitSeconds: 25, questionText: "Name the plant tissue that transports water and mineral ions from roots upward.", answer: "xylem", acceptedAnswers: ["xylem tissue"], shortcutSolution: "Xylem moves water; phloem moves assimilates.", fullSolution: "Xylem vessels conduct water and dissolved mineral ions and also provide support.", commonTrap: "Answering phloem.", repeatedPattern: "plant tissue from transport function", patternFamily: "plant transport" }),
  q({ subject: "BIOLOGY", topic: "Reproduction", subtopic: "Mosquito development", roundType: "TRUE_FALSE", difficulty: "EASY", timeLimitSeconds: 20, questionText: "True or False: The mosquito life cycle includes egg, larva, pupa, and adult stages.", answer: "True", acceptedAnswers: ["T"], shortcutSolution: "Mosquitoes undergo complete metamorphosis.", fullSolution: "The aquatic larva and pupa precede the winged adult, completing four distinct stages.", commonTrap: "Omitting the pupal stage.", repeatedPattern: "insect life-cycle order", patternFamily: "development", ghanaContext: true, tags: ["mosquito", "malaria"] }),
  q({ subject: "BIOLOGY", topic: "Nutrition", subtopic: "Food preservation", roundType: "ROUND_ONE", difficulty: "MEDIUM", timeLimitSeconds: 40, questionText: "Why does drying gari reduce microbial spoilage?", answer: "it lowers water availability", acceptedAnswers: ["reduces moisture", "lowers water activity", "dehydration"], shortcutSolution: "Less available water means slower microbial metabolism and reproduction.", fullSolution: "Drying lowers water activity, limiting microbial growth and many enzyme-controlled spoilage reactions.", commonTrap: "Claiming drying sterilizes the food completely.", repeatedPattern: "preservation method from microbial requirement", patternFamily: "food biology", ghanaContext: true, tags: ["gari", "dehydration"] }),
  q({ subject: "BIOLOGY", topic: "Cell Biology", subtopic: "Osmosis", roundType: "TRUE_FALSE", difficulty: "MEDIUM", timeLimitSeconds: 25, questionText: "True or False: A plant cell placed in a strongly hypertonic solution may undergo plasmolysis.", answer: "True", acceptedAnswers: ["T"], shortcutSolution: "Water leaves by osmosis, pulling the membrane from the wall.", fullSolution: "A hypertonic external solution lowers water potential outside, causing net water loss and plasmolysis.", commonTrap: "Thinking the rigid cell wall prevents all volume change.", repeatedPattern: "predict cell response to tonicity", patternFamily: "membrane transport" }),
  q({ subject: "BIOLOGY", topic: "Genetics", subtopic: "DNA base pairing", roundType: "SPEED_RACE", difficulty: "MEDIUM", timeLimitSeconds: 20, questionText: "If a double-stranded DNA sample contains 28% adenine, what percentage is guanine?", answer: "22%", acceptedAnswers: ["22", "22 percent"], shortcutSolution: "A=T=28%, leaving 44% for G+C; each is 22%.", fullSolution: "Chargaff's rule gives A=T and G=C in double-stranded DNA.", commonTrap: "Subtracting 28 from 50 without explaining complementary pairs.", repeatedPattern: "base composition by Chargaff rule", patternFamily: "molecular genetics" }),
  q({ subject: "BIOLOGY", topic: "Ecology", subtopic: "Water pollution", roundType: "ROUND_ONE", difficulty: "MEDIUM", timeLimitSeconds: 45, questionText: "Explain why nutrient-rich runoff into a lake can eventually lower dissolved oxygen.", answer: "eutrophication and decomposition consume oxygen", acceptedAnswers: ["algal bloom followed by aerobic decomposition", "eutrophication"], shortcutSolution: "More nutrients → algal bloom → decay → microbial respiration uses oxygen.", fullSolution: "Excess nutrients stimulate producers; when biomass dies, decomposers respire rapidly and reduce dissolved oxygen.", commonTrap: "Saying algae directly remove all oxygen only by photosynthesis.", repeatedPattern: "cause-effect chain in eutrophication", patternFamily: "aquatic ecology" }),
  q({ subject: "BIOLOGY", topic: "Human Physiology", subtopic: "Thermoregulation", roundType: "RIDDLE", difficulty: "MEDIUM", timeLimitSeconds: 60, questionText: "Identify the process from the clues.", answer: "sweating", acceptedAnswers: ["perspiration"], shortcutSolution: "Evaporation of a skin secretion causing cooling is sweating.", fullSolution: "Sweat glands secrete fluid; its evaporation removes latent heat and helps regulate body temperature.", commonTrap: "Answering respiration, which also loses some water but is not the skin response.", repeatedPattern: "identify homeostatic response", patternFamily: "thermoregulation", riddleClues: clues(["I am a response to excessive body heat.", "Glands in the skin produce my fluid.", "My effectiveness depends partly on humidity.", "My evaporation cools the body."]) }),
  q({ subject: "BIOLOGY", topic: "Genetics", subtopic: "Sex linkage", roundType: "ROUND_ONE", difficulty: "HARD", timeLimitSeconds: 55, questionText: "A carrier woman for an X-linked recessive condition has children with an unaffected man. What fraction of their sons is expected to be affected?", answer: "1/2", acceptedAnswers: ["50%", "0.5"], shortcutSolution: "Each son gets Y from father and has a 1/2 chance of receiving the affected X from mother.", fullSolution: "The carrier mother produces normal and affected X-bearing eggs in equal proportions.", commonTrap: "Giving 1/4, which is the fraction among all children under equal sex probability.", repeatedPattern: "X-linked carrier cross", patternFamily: "sex-linked inheritance" }),
  q({ subject: "BIOLOGY", topic: "Respiration", subtopic: "Respiratory quotient", roundType: "SPEED_RACE", difficulty: "HARD", timeLimitSeconds: 30, questionText: "A tissue consumes 50 cm³ O₂ and releases 35 cm³ CO₂. Find its respiratory quotient.", answer: "0.7", shortcutSolution: "RQ = CO₂ produced/O₂ consumed = 35/50.", fullSolution: "The respiratory quotient is 0.70, suggesting substantial lipid oxidation.", commonTrap: "Inverting the ratio.", repeatedPattern: "respiratory quotient calculation", patternFamily: "cellular respiration" }),
  q({ subject: "BIOLOGY", topic: "Plant Biology", subtopic: "Transpiration", roundType: "TRUE_FALSE", difficulty: "HARD", timeLimitSeconds: 30, questionText: "True or False: Harmattan conditions can increase transpiration when dry air steepens the water-vapour gradient from leaf to atmosphere.", answer: "True", acceptedAnswers: ["T"], shortcutSolution: "Lower humidity outside increases the diffusion gradient.", fullSolution: "Dry air lowers external water-vapour concentration, often increasing transpiration if stomata remain open.", commonTrap: "Assuming cool weather always means low transpiration.", repeatedPattern: "environmental factor affecting transpiration", patternFamily: "plant water relations", ghanaContext: true, tags: ["harmattan", "humidity"] }),
  q({ subject: "BIOLOGY", topic: "Evolution", subtopic: "Natural selection", roundType: "ROUND_ONE", difficulty: "HARD", timeLimitSeconds: 55, questionText: "Explain why frequent misuse of an antibiotic can increase the proportion of resistant bacteria.", answer: "selection favors resistant variants", acceptedAnswers: ["natural selection", "susceptible bacteria die while resistant bacteria reproduce"], shortcutSolution: "The drug selects existing resistant variants; it does not teach bacteria to resist.", fullSolution: "Susceptible bacteria are removed, while resistant bacteria survive and contribute more descendants, increasing resistance frequency.", commonTrap: "Saying individual bacteria deliberately adapt because they need to.", repeatedPattern: "selection under environmental pressure", patternFamily: "evolutionary mechanisms" }),
  q({ subject: "BIOLOGY", topic: "Excretion", subtopic: "Nephron function", roundType: "ROUND_ONE", difficulty: "HARD", timeLimitSeconds: 60, questionText: "Name the nephron process that moves glucose from filtrate back into blood and state its main location.", answer: "selective reabsorption in the proximal convoluted tubule", acceptedAnswers: ["active reabsorption in PCT", "PCT selective reabsorption"], shortcutSolution: "Useful solutes are reclaimed mainly in the proximal convoluted tubule.", fullSolution: "Glucose is selectively reabsorbed, largely by sodium-glucose cotransport in the proximal convoluted tubule.", commonTrap: "Calling the process ultrafiltration, which occurs at the glomerulus.", repeatedPattern: "nephron process and location", patternFamily: "renal physiology" }),
  q({ subject: "BIOLOGY", topic: "Nutrition", subtopic: "Enzyme action", roundType: "RIDDLE", difficulty: "HARD", timeLimitSeconds: 60, questionText: "Identify the digestive enzyme from the clues.", answer: "lipase", acceptedAnswers: ["a lipase"], shortcutSolution: "An enzyme hydrolysing fats to fatty acids and glycerol is lipase.", fullSolution: "Lipases catalyse hydrolysis of triglycerides; pancreatic lipase acts in the small intestine.", commonTrap: "Answering amylase, which digests starch.", repeatedPattern: "identify enzyme from substrate and products", patternFamily: "digestion", riddleClues: clues(["I am a hydrolytic digestive enzyme.", "My substrate is not a carbohydrate or protein.", "Bile helps my work by increasing substrate surface area.", "I digest lipids into fatty acids and glycerol."]) }),
  q({ subject: "BIOLOGY", topic: "Human Physiology", subtopic: "Cardiac output", roundType: "PROBLEM_OF_THE_DAY", difficulty: "HARD", timeLimitSeconds: 300, questionText: "A student's heart rate rises from 70 to 150 beats/min during exercise while stroke volume rises from 70 to 110 cm³. Calculate resting and exercise cardiac output and the percentage increase.", answer: "4.9 L/min; 16.5 L/min; 237%", acceptedAnswers: ["4.9, 16.5, 236.7%"], shortcutSolution: "CO=HR×SV. Rest=4900 cm³/min; exercise=16500; increase=(11.6/4.9)×100.", fullSolution: "Cardiac output is heart rate multiplied by stroke volume. Converting to litres gives 4.9 and 16.5 L/min; percentage increase is about 237%.", commonTrap: "Calculating exercise output correctly but reporting the ratio as the percentage increase.", repeatedPattern: "cardiac output and percentage change", patternFamily: "circulatory calculations", examinerFocus: "Combine physiological rates, unit conversion, and percentage increase.", markingScheme: "3 marks rest; 3 marks exercise; 3 marks percentage; 1 mark units." }),
  q({ subject: "BIOLOGY", topic: "Plant Biology", subtopic: "Photosynthesis limiting factors", roundType: "PROBLEM_OF_THE_DAY", difficulty: "HARD", timeLimitSeconds: 300, questionText: "A leaf's photosynthetic rate rises with light intensity, then plateaus. When CO₂ concentration is increased, the plateau rises. Explain both observations.", answer: "light is limiting first; carbon dioxide becomes limiting at the first plateau", acceptedAnswers: ["light then CO2 limitation"], shortcutSolution: "The factor that changes the rate is limiting; the plateau shifts when CO₂ is raised.", fullSolution: "At low light, photon supply limits reactions. At higher light another factor, demonstrated here to be CO₂ availability, limits carbon fixation.", commonTrap: "Saying photosynthesis has stopped at the plateau.", repeatedPattern: "interpret limiting-factor graph", patternFamily: "photosynthesis", examinerFocus: "Use experimental changes to identify successive limiting factors.", markingScheme: "4 marks low-light region; 4 marks plateau/CO₂; 2 marks graph interpretation." }),
  q({ subject: "BIOLOGY", topic: "Reproduction", subtopic: "Malaria transmission", roundType: "PROBLEM_OF_THE_DAY", difficulty: "NSMQ_FINAL_LEVEL", timeLimitSeconds: 360, questionText: "In a community, 60% of mosquito breeding containers are removed. The remaining containers produce 50% more larvae each because competition falls. Assuming adult survival is unchanged, estimate the percentage change in total adult mosquito production.", answer: "40% decrease", acceptedAnswers: ["decreases by 40%", "-40%"], shortcutSolution: "Remaining fraction 0.4 × production factor 1.5 = 0.6 of original.", fullSolution: "After removal, 40% of sites remain. Compensatory production raises output to 0.4×1.5=0.60 of baseline, a 40% reduction.", commonTrap: "Subtracting 50% from 60% and claiming only a 10% reduction.", repeatedPattern: "multiplicative ecological intervention", patternFamily: "population control", ghanaContext: true, tags: ["mosquito", "malaria"], examinerFocus: "Model compensatory density dependence multiplicatively.", markingScheme: "4 marks remaining fraction; 3 marks compensation; 3 marks percentage change." }),
  q({ subject: "BIOLOGY", topic: "Genetics", subtopic: "Linkage mapping", roundType: "PROBLEM_OF_THE_DAY", difficulty: "NSMQ_FINAL_LEVEL", timeLimitSeconds: 360, questionText: "A test cross produces 420 AB, 400 ab, 90 Ab and 90 aB offspring. Calculate recombination frequency and map distance.", answer: "18%; 18 cM", acceptedAnswers: ["18 percent, 18 map units"], shortcutSolution: "Recombinants=180; total=1000; 180/1000×100=18%.", fullSolution: "The less frequent classes are recombinant. Recombination frequency is 18%, corresponding to approximately 18 centimorgans.", commonTrap: "Treating the two largest parental classes as recombinants.", repeatedPattern: "test-cross linkage map", patternFamily: "genetic mapping", examinerFocus: "Identify parental/recombinant classes before calculating map distance.", markingScheme: "3 marks class identification; 4 marks frequency; 3 marks map interpretation." }),
  q({ subject: "BIOLOGY", topic: "Respiration", subtopic: "Oxidative phosphorylation", roundType: "PROBLEM_OF_THE_DAY", difficulty: "NSMQ_FINAL_LEVEL", timeLimitSeconds: 360, questionText: "A poison blocks the final electron acceptor step in the mitochondrial electron transport chain. Predict immediate effects on oxygen use, proton gradient, ATP synthesis, and reduced NAD.", answer: "oxygen use stops; proton gradient falls; ATP synthesis falls; reduced NAD accumulates", acceptedAnswers: ["O2 consumption stops, gradient collapses, ATP decreases, NADH rises"], shortcutSolution: "Block electron flow: no O₂ reduction, no proton pumping, little ATP, and upstream carriers stay reduced.", fullSolution: "Without terminal electron transfer to oxygen, the chain backs up. Proton pumping ceases, the gradient dissipates, oxidative phosphorylation declines, and NADH cannot be efficiently oxidized.", commonTrap: "Claiming glycolysis must stop immediately in every cell.", repeatedPattern: "predict pathway effects from blocked step", patternFamily: "cellular respiration", examinerFocus: "Trace causality through coupled electron transport and chemiosmosis.", markingScheme: "2 marks each predicted variable; 2 marks causal link." }),
  q({ subject: "BIOLOGY", topic: "Ecology", subtopic: "Capture-recapture", roundType: "PROBLEM_OF_THE_DAY", difficulty: "NSMQ_FINAL_LEVEL", timeLimitSeconds: 360, questionText: "Researchers mark 120 tilapia and release them. Later they catch 150 fish, of which 30 are marked. Estimate population size, then state two assumptions of the method.", answer: "600 fish; population closed and marks retained/mixed randomly", acceptedAnswers: ["600; closed population; no mark loss"], shortcutSolution: "N ≈ (120×150)/30 = 600.", fullSolution: "The Lincoln index estimates 600 fish. Validity requires assumptions such as no migration/birth/death, retained marks, equal catchability, and thorough mixing.", commonTrap: "Dividing the second sample by marked recaptures without multiplying by the first marked group.", repeatedPattern: "capture-recapture estimate and assumptions", patternFamily: "population ecology", ghanaContext: true, tags: ["tilapia", "fishing"], examinerFocus: "Calculate an ecological estimate and evaluate its assumptions.", markingScheme: "5 marks estimate; 2.5 marks per valid assumption." }),
];
