import type { ExpandedQuestion } from "./expanded-questions";

const encouragement = "Good training. Connect the science to the Ghanaian example, then practise the underlying pattern again.";
const clues = (values: string[]) => {
  const points = [5, 4, 3, 3, 3];
  return values.map((clueText, index) => ({ clueNumber: index + 1, clueText, points: points[index] }));
};

const q = (
  question: Omit<ExpandedQuestion, "encouragement" | "acceptedAnswers" | "tags" | "ghanaContext"> &
    Partial<Pick<ExpandedQuestion, "acceptedAnswers" | "tags">>,
): ExpandedQuestion => ({
  acceptedAnswers: [],
  tags: ["ghana-context", question.topic.toLowerCase()],
  ghanaContext: true,
  encouragement,
  ...question,
});

export const ghanaContextQuestions: ExpandedQuestion[] = [
  // Eight Ghana-context riddles
  q({
    subject: "BIOLOGY",
    topic: "Nutrition",
    subtopic: "Food preservation",
    roundType: "RIDDLE",
    difficulty: "MEDIUM",
    timeLimitSeconds: 60,
    questionText: "Identify the preservation process from the clues.",
    answer: "dehydration",
    acceptedAnswers: ["drying", "food dehydration"],
    shortcutSolution: "Removing water to limit microbial growth is dehydration.",
    fullSolution: "Dehydration lowers moisture availability and water activity, slowing microbial growth and spoilage reactions.",
    commonTrap: "Calling the process sterilization; drying does not necessarily kill every microorganism.",
    repeatedPattern: "identify preservation method from water removal",
    patternFamily: "food preservation",
    tags: ["gari", "dehydration", "food preservation"],
    riddleClues: clues([
      "I am common in food preservation.",
      "I reduce the amount of water available to microorganisms.",
      "You see me when gari is roasted.",
      "I am the removal of water from a substance.",
    ]),
  }),
  q({
    subject: "PHYSICS",
    topic: "Mechanics",
    subtopic: "Energy conversion",
    roundType: "RIDDLE",
    difficulty: "MEDIUM",
    timeLimitSeconds: 60,
    questionText: "Identify the energy technology from the clues.",
    answer: "hydroelectric power",
    acceptedAnswers: ["hydropower", "hydroelectricity"],
    shortcutSolution: "Falling stored water driving turbines identifies hydroelectric power.",
    fullSolution: "Hydroelectric stations convert gravitational potential energy of stored water into kinetic, mechanical, and then electrical energy.",
    commonTrap: "Answering solar power because both are renewable energy sources.",
    repeatedPattern: "identify technology from energy transformations",
    patternFamily: "energy conversion",
    tags: ["Akosombo", "hydroelectric power"],
    riddleClues: clues([
      "I convert stored water energy into electrical energy.",
      "I am linked with a major lake in Ghana.",
      "I use turbines and generators.",
      "Akosombo is a famous example.",
    ]),
  }),
  q({
    subject: "CHEMISTRY",
    topic: "Organic Chemistry",
    subtopic: "Fermentation",
    roundType: "RIDDLE",
    difficulty: "MEDIUM",
    timeLimitSeconds: 60,
    questionText: "Identify the biochemical process from the clues.",
    answer: "lactic acid fermentation",
    acceptedAnswers: ["lactic fermentation", "lactate fermentation"],
    shortcutSolution: "Microbial acid production that sours dough points to lactic acid fermentation.",
    fullSolution: "Lactic acid bacteria metabolize carbohydrates and produce lactic acid, lowering pH and contributing the sour taste of fermented dough.",
    commonTrap: "Answering alcoholic fermentation, whose characteristic products include ethanol and carbon dioxide.",
    repeatedPattern: "identify fermentation from product and food",
    patternFamily: "biochemical processes",
    tags: ["kenkey", "fermentation", "lactic acid"],
    riddleClues: clues([
      "Microorganisms carry me out without relying on oxygen as the final electron acceptor.",
      "I lower pH and help develop a sour taste.",
      "One of my important products is lactic acid.",
      "I occur while kenkey dough ferments.",
    ]),
  }),
  q({
    subject: "CHEMISTRY",
    topic: "Rates of Reaction",
    subtopic: "Cocoa processing",
    roundType: "RIDDLE",
    difficulty: "HARD",
    timeLimitSeconds: 60,
    questionText: "Identify the processing stage from the clues.",
    answer: "cocoa fermentation",
    acceptedAnswers: ["fermentation of cocoa beans", "cocoa bean fermentation"],
    shortcutSolution: "Microbial breakdown of cocoa pulp before drying is cocoa fermentation.",
    fullSolution: "Yeasts and bacteria act on cocoa pulp, producing heat and metabolites that initiate flavour development and reduce bean bitterness.",
    commonTrap: "Answering roasting, which occurs later and uses direct heating.",
    repeatedPattern: "identify food-processing stage from microbial action",
    patternFamily: "fermentation",
    tags: ["cocoa", "fermentation"],
    riddleClues: clues([
      "I am an early biological stage in processing a major Ghanaian crop.",
      "Microorganisms act on sugary pulp during me.",
      "I generate heat and begin important flavour changes.",
      "I occur before cocoa beans are dried.",
    ]),
  }),
  q({
    subject: "MATHEMATICS",
    topic: "Geometry",
    subtopic: "Transformations",
    roundType: "RIDDLE",
    difficulty: "MEDIUM",
    timeLimitSeconds: 60,
    questionText: "Identify the geometric property from the clues.",
    answer: "symmetry",
    acceptedAnswers: ["geometric symmetry"],
    shortcutSolution: "A design matching itself after reflection or rotation displays symmetry.",
    fullSolution: "Symmetry describes invariance under transformations such as reflection, rotation, or translation.",
    commonTrap: "Answering congruence, which compares figures rather than a design with its transformed self.",
    repeatedPattern: "identify transformation property from design",
    patternFamily: "transformational geometry",
    tags: ["kente", "symmetry"],
    riddleClues: clues([
      "I bring mathematical order to repeated designs.",
      "A figure may possess several types of me.",
      "Reflection and rotation can reveal me.",
      "Kente patterns often display me.",
    ]),
  }),
  q({
    subject: "CHEMISTRY",
    topic: "Acids, Bases, and Salts",
    subtopic: "Separation methods",
    roundType: "RIDDLE",
    difficulty: "MEDIUM",
    timeLimitSeconds: 60,
    questionText: "Identify the separation process from the clues.",
    answer: "evaporation",
    acceptedAnswers: ["evaporation to dryness", "solar evaporation"],
    shortcutSolution: "Removing water as vapour to leave dissolved salt is evaporation.",
    fullSolution: "Solar heating allows water molecules to escape from brine, concentrating it until salt crystals can form.",
    commonTrap: "Answering filtration, which cannot remove dissolved salt from water.",
    repeatedPattern: "identify separation method from volatile solvent",
    patternFamily: "separation techniques",
    tags: ["salt winning", "evaporation"],
    riddleClues: clues([
      "I separate a dissolved solid from a volatile liquid.",
      "Sunlight can supply the energy I require.",
      "I concentrate brine as water molecules escape.",
      "Salt winning along Ghana's coast makes use of me.",
    ]),
  }),
  q({
    subject: "PHYSICS",
    topic: "Heat and Thermodynamics",
    subtopic: "Evaporative cooling",
    roundType: "RIDDLE",
    difficulty: "HARD",
    timeLimitSeconds: 60,
    questionText: "Identify the cooling process from the clues.",
    answer: "evaporative cooling",
    acceptedAnswers: ["cooling by evaporation", "evaporation"],
    shortcutSolution: "High-energy molecules escaping from a wet surface cause evaporative cooling.",
    fullSolution: "Evaporation preferentially removes energetic molecules, lowering the average kinetic energy and temperature of the remaining liquid.",
    commonTrap: "Saying porous clay produces cold energy.",
    repeatedPattern: "identify thermal process from molecular escape",
    patternFamily: "thermal physics",
    tags: ["clay pot", "evaporative cooling"],
    riddleClues: clues([
      "I lower temperature without a refrigerator.",
      "I work best when surrounding air is not already saturated.",
      "The fastest molecules escape and carry energy away.",
      "A porous clay pot can use me to cool water.",
    ]),
  }),
  q({
    subject: "BIOLOGY",
    topic: "Reproduction",
    subtopic: "Insect development",
    roundType: "RIDDLE",
    difficulty: "MEDIUM",
    timeLimitSeconds: 60,
    questionText: "Identify the developmental process from the clues.",
    answer: "complete metamorphosis",
    acceptedAnswers: ["holometabolous development", "metamorphosis"],
    shortcutSolution: "Egg, larva, pupa, and adult identify complete metamorphosis.",
    fullSolution: "Complete metamorphosis has four distinct stages. Mosquito larvae and pupae are aquatic before the winged adult emerges.",
    commonTrap: "Answering incomplete metamorphosis, which has no pupal stage.",
    repeatedPattern: "identify development type from life-cycle stages",
    patternFamily: "life cycles",
    tags: ["mosquito", "malaria", "life cycle"],
    riddleClues: clues([
      "I describe a major change in body form during development.",
      "My immature stage may live in water while my adult flies.",
      "I include a pupal stage.",
      "The mosquito passes through egg, larva, pupa, and adult during me.",
    ]),
  }),

  // Eight Ghana-context speed-race questions
  q({
    subject: "PHYSICS", topic: "Mechanics", subtopic: "Speed", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 15,
    questionText: "A trotro travels 600 m in 40 s. Find its average speed.",
    answer: "15 m/s", acceptedAnswers: ["15", "15m/s"],
    shortcutSolution: "Speed = 600/40 = 15 m/s.",
    fullSolution: "Average speed is distance divided by elapsed time.",
    commonTrap: "Multiplying distance and time.",
    repeatedPattern: "distance divided by time", patternFamily: "kinematics", tags: ["trotro", "speed"],
  }),
  q({
    subject: "PHYSICS", topic: "Pressure and Fluids", subtopic: "Weight", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 15,
    questionText: "A market scale supports a 6 kg bag. Using g = 10 m/s², find its weight.",
    answer: "60 N", acceptedAnswers: ["60", "60N"],
    shortcutSolution: "W = mg = 6 × 10.",
    fullSolution: "Weight is the gravitational force on the bag, equal to mass times gravitational field strength.",
    commonTrap: "Reporting 6 kg as a force.",
    repeatedPattern: "mass to weight", patternFamily: "forces", tags: ["market scale", "weight"],
  }),
  q({
    subject: "CHEMISTRY", topic: "Organic Chemistry", subtopic: "Plant hormones", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 15,
    questionText: "Name the gaseous hormone that promotes plantain ripening.",
    answer: "ethene", acceptedAnswers: ["ethylene"],
    shortcutSolution: "Fruit ripening points to ethene.",
    fullSolution: "Ethene is a gaseous plant hormone that promotes ripening responses in climacteric fruits.",
    commonTrap: "Answering ethanol because its name sounds similar.",
    repeatedPattern: "identify hormone from function", patternFamily: "organic compounds in biology", tags: ["plantain", "ethene"],
  }),
  q({
    subject: "CHEMISTRY", topic: "Acids, Bases, and Salts", subtopic: "Salt winning", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 15,
    questionText: "Which physical process removes water from brine during traditional salt winning?",
    answer: "evaporation", acceptedAnswers: ["solar evaporation"],
    shortcutSolution: "Water leaves the brine as vapour.",
    fullSolution: "Solar energy drives evaporation, increasing salt concentration.",
    commonTrap: "Answering filtration, which does not remove dissolved ions.",
    repeatedPattern: "separation process from context", patternFamily: "separation techniques", tags: ["salt winning", "evaporation"],
  }),
  q({
    subject: "BIOLOGY", topic: "Plant Biology", subtopic: "Transpiration", roundType: "SPEED_RACE", difficulty: "MEDIUM", timeLimitSeconds: 20,
    questionText: "During Harmattan, lower air humidity usually makes the leaf-to-air water-vapour gradient steeper or shallower?",
    answer: "steeper", acceptedAnswers: ["steeper gradient", "greater"],
    shortcutSolution: "Drier air means a larger difference from moist leaf air spaces.",
    fullSolution: "Lower external humidity increases the water-vapour concentration gradient, often increasing transpiration.",
    commonTrap: "Assuming cooler conditions always make the gradient smaller.",
    repeatedPattern: "predict diffusion gradient from humidity", patternFamily: "plant water relations", tags: ["Harmattan", "humidity"],
  }),
  q({
    subject: "BIOLOGY", topic: "Reproduction", subtopic: "Mosquito life cycle", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 15,
    questionText: "Which mosquito life-cycle stage comes immediately before the adult?",
    answer: "pupa", acceptedAnswers: ["pupal stage"],
    shortcutSolution: "Egg → larva → pupa → adult.",
    fullSolution: "Mosquitoes undergo complete metamorphosis, and the adult emerges from the pupa.",
    commonTrap: "Answering larva and skipping the pupal stage.",
    repeatedPattern: "life-cycle sequence recall", patternFamily: "development", tags: ["mosquito", "malaria"],
  }),
  q({
    subject: "MATHEMATICS", topic: "Geometry", subtopic: "Rotational symmetry", roundType: "SPEED_RACE", difficulty: "EASY", timeLimitSeconds: 15,
    questionText: "A square Adinkra tile has what order of rotational symmetry?",
    answer: "4", acceptedAnswers: ["four"],
    shortcutSolution: "It matches at 90°, 180°, 270°, and 360°.",
    fullSolution: "A square maps onto itself four times during one complete turn.",
    commonTrap: "Counting only three positions before 360°.",
    repeatedPattern: "rotational symmetry order", patternFamily: "transformations", tags: ["Adinkra", "geometry"],
  }),
  q({
    subject: "MATHEMATICS", topic: "Sequences and Series", subtopic: "Repeating patterns", roundType: "SPEED_RACE", difficulty: "MEDIUM", timeLimitSeconds: 20,
    questionText: "A kente colour motif repeats every 6 strips. Which motif position matches strip 26?",
    answer: "2", acceptedAnswers: ["second", "position 2"],
    shortcutSolution: "26 leaves remainder 2 when divided by 6.",
    fullSolution: "Periodic positions are determined modulo 6; 26 ≡ 2 mod 6.",
    commonTrap: "Using the quotient rather than the remainder.",
    repeatedPattern: "cyclic position by remainder", patternFamily: "modular patterns", tags: ["kente", "patterns"],
  }),

  // Two Ghana-context true/false questions
  q({
    subject: "CHEMISTRY", topic: "Rates of Reaction", subtopic: "Cocoa fermentation", roundType: "TRUE_FALSE", difficulty: "MEDIUM", timeLimitSeconds: 25,
    questionText: "True or False: Cocoa fermentation involves microbial activity and can generate heat.",
    answer: "True", acceptedAnswers: ["T"],
    shortcutSolution: "Microbial metabolism during cocoa fermentation releases energy.",
    fullSolution: "Yeasts and bacteria metabolize cocoa pulp, producing heat and compounds important for flavour development.",
    commonTrap: "Confusing fermentation with the later non-biological drying stage.",
    repeatedPattern: "recognize biological food processing", patternFamily: "fermentation", tags: ["cocoa", "fermentation"],
  }),
  q({
    subject: "PHYSICS", topic: "Heat and Thermodynamics", subtopic: "Clay-pot cooling", roundType: "TRUE_FALSE", difficulty: "MEDIUM", timeLimitSeconds: 25,
    questionText: "True or False: A porous clay pot cools water mainly because evaporation removes energetic molecules from the water.",
    answer: "True", acceptedAnswers: ["T"],
    shortcutSolution: "Evaporation carries latent heat away.",
    fullSolution: "Water reaches the outer porous surface and evaporates; the escaping molecules remove energy, lowering the remaining water's temperature.",
    commonTrap: "Claiming the clay chemically absorbs heat and destroys it.",
    repeatedPattern: "molecular explanation of evaporative cooling", patternFamily: "thermal physics", tags: ["clay pot", "cooling"],
  }),

  // One additional Ghana-context Round 1 question
  q({
    subject: "MATHEMATICS", topic: "Geometry", subtopic: "Reflection symmetry", roundType: "ROUND_ONE", difficulty: "MEDIUM", timeLimitSeconds: 35,
    questionText: "A stylized Adinkra design has two perpendicular mirror lines through its centre. How many lines of reflection symmetry does the design have?",
    answer: "2", acceptedAnswers: ["two"],
    shortcutSolution: "Count the distinct mirror lines described.",
    fullSolution: "Each stated line divides the design into matching reflected halves, giving two lines of symmetry.",
    commonTrap: "Counting the four regions instead of the two mirror lines.",
    repeatedPattern: "count reflection axes", patternFamily: "transformations", tags: ["Adinkra", "reflection symmetry"],
  }),
];
